/* 82 east wing: south facade photo fit; concealed northern junction inferred. */
(function(Y){'use strict';const A=Y.Architecture30,prev=A.render,G=Y.Geo,cut=-123.8,W=-121.7,E=-116.7,S=-294.95,C=(W+E)/2;
const north=x=>-311.974-(x+120.146)*.038744,join=x=>-304.823-(x+119.873)*.037855;
const color={brick:'#979b92',roof:'#555c55',red:'#943d29',stone:['#969181','#a39680','#b2a590','#8e968b']};
function clip(poly){const out=[];for(let i=0;i<poly.length;i++){let a=poly[i],b=poly[(i+1)%poly.length],da=a[0]-cut,db=b[0]-cut;if(da<=1e-9)out.push(a);if((da<=0)!==(db<=0)){let t=da/(da-db);out.push(a.map((v,j)=>v+(b[j]-v)*t));}}return out;}
function clean(g){const out=new G.Geometry();for(let i=0;i<g.v.length;i+=24){const p=[0,8,16].map(k=>g.v.slice(i+k,i+k+3).map(Math.fround)),a=Y.M.sub(p[1],p[0]),c=Y.M.sub(p[2],p[0]);if(Math.hypot(...Y.M.cross(a,c))>1e-10)out.v.push(...g.v.slice(i,i+24));}return out;}
function trim(g,m){const o=new G.Geometry();for(let i=0;i<g.v.length;i+=24){let p=[0,8,16].map(k=>{let q=g.v.slice(i+k,i+k+8);if(m){const x=q[0],y=q[1],z=q[2];q[0]=m[0]*x+m[4]*y+m[8]*z+m[12];q[1]=m[1]*x+m[5]*y+m[9]*z+m[13];q[2]=m[2]*x+m[6]*y+m[10]*z+m[14];}return q;});p=clip(p);for(let j=1;j+1<p.length;j++){if(m)o.tri(p[0].slice(0,3),p[j].slice(0,3),p[j+1].slice(0,3),[p[0].slice(6),p[j].slice(6),p[j+1].slice(6)]);else o.v.push(...p[0],...p[j],...p[j+1]);}}return clean(o);}
A.render=function(b,f,add){if(f.properties.id!=='way/1075644754')return prev.call(this,b,f,add);const emit=b.e.add;let seq=0,oldRoof,ret;
b.e.add=function(k,g,m,c,p,uv){if(p[1]===400&&(k.startsWith('math42-')||k==='box')){if(k==='math42-continuous-roof-400')oldRoof=g;
 // Existing house source only: gate names are explicitly excluded.
 if(k==='box'){const maxx=m[12]+(Math.abs(m[0])+Math.abs(m[4])+Math.abs(m[8]))*.5;if(maxx>cut){const t=trim(g,m);if(t.v.length)return emit.call(this,'400-wing102-old-box-'+seq++,t,Y.M.identity(),c,p,uv);return;}}
 else{g=trim(g);k='400-wing102-retained-'+k;}}
 return emit.call(this,k,g,m,c,p,uv);};try{ret=prev.call(this,b,f,add);}finally{b.e.add=emit;}if(!oldRoof)throw Error('400 original roof missing');
const oldId=b.id;b.id=400;const mesh=(n,g,c,mat)=>b.mesh('400-wing102-'+n,clean(g),0,0,0,1,1,1,c,mat);
function oldY(x,z){for(let i=0;i<oldRoof.v.length;i+=24){let a=oldRoof.v.slice(i,i+3),q=oldRoof.v.slice(i+8,i+11),r=oldRoof.v.slice(i+16,i+19),d=(q[2]-r[2])*(a[0]-r[0])+(r[0]-q[0])*(a[2]-r[2]);if(Math.abs(d)<1e-10)continue;let u=((q[2]-r[2])*(x-r[0])+(r[0]-q[0])*(z-r[2]))/d,v=((r[2]-a[2])*(x-r[0])+(a[0]-r[0])*(z-r[2]))/d;if(u>=-1e-5&&v>=-1e-5&&u+v<=1.00001)return u*a[1]+v*q[1]+(1-u-v)*r[1];}return 4.8;}
// Two independent roofs: extruded original transverse section, and a
// constant-section longitudinal wing. Their exposed faces meet on real valleys.
const lowY=x=>3.3+2.2*Math.pow(Math.max(0,1-Math.abs(x-C)/2.5),1.38);
const highY=(x,z)=>{const t=(z-north(x))/(join(x)-north(x));return oldY(cut,north(cut)+t*(join(cut)-north(cut)));};
const roofY=(x,z)=>lowY(x);
const body=new G.Geometry(),roof=new G.Geometry(),rolls=new G.Geometry(),front=new G.Geometry(),reveal=new G.Geometry(),glass=new G.Geometry(),junction=new G.Geometry(),trimRoof=new G.Geometry();
function wall(a,c,top){for(let i=0;i<48;i++){const t=i/48,u=(i+1)/48,x=a[0]+(c[0]-a[0])*t,z=a[1]+(c[1]-a[1])*t,xx=a[0]+(c[0]-a[0])*u,zz=a[1]+(c[1]-a[1])*u;body.quad([x,.08,z],[xx,.08,zz],[xx,top(xx,zz),zz],[x,top(x,z),z]);}}
wall([E,S],[E,join(E)],lowY);wall([E,join(E)],[E,north(E)],highY);wall([E,north(E)],[cut,north(cut)],highY);wall([cut,join(cut)],[W,join(W)],highY);wall([W,join(W)],[W,S],lowY);
const seamZ=[];for(let i=0;i<oldRoof.v.length;i+=24){const ps=[0,8,16].map(k=>oldRoof.v.slice(i+k,i+k+3));for(let j=0;j<3;j++){const a=ps[j],q=ps[(j+1)%3],da=a[0]-cut,dq=q[0]-cut;if(Math.abs(da)<1e-8)seamZ.push(a[2]);if(da*dq<0){const t=da/(da-dq);seamZ.push(a[2]+(q[2]-a[2])*t);}}}
const seamT=[0,.5,1,...seamZ.filter(z=>z>north(cut)+1e-8&&z<join(cut)-1e-8).map(z=>(z-north(cut))/(join(cut)-north(cut)))].sort((a,b)=>a-b).filter((v,i,a)=>!i||v-a[i-1]>1e-10);
const joinXs=[...new Set([...Array.from({length:65},(_,i)=>cut+(E-cut)*i/64),...Array.from({length:49},(_,i)=>W+(E-W)*i/48),W,C,E])].sort((a,b)=>a-b).filter((x,i,a)=>!i||Math.abs(x-a[i-1])>1e-6),at=(a,c,t)=>t===0?a:t===1?c:a+(c-a)*t;
// Each cell is triangulated first; clipping the difference of two planar
// triangles creates identical intersection vertices on both roof surfaces.
function envelope(ps,overlap){const packed=ps.map(p=>[p[0],highY(p[0],p[1]),p[1],lowY(p[0])]);
 function half(poly,sign){const out=[];for(let i=0;i<poly.length;i++){const a=poly[i],q=poly[(i+1)%poly.length],d=(a[1]-a[3])*sign,e=(q[1]-q[3])*sign;if(d>=0)out.push(a);if((d>=0)!==(e>=0)){const t=d/(d-e);out.push(a.map((v,k)=>v+(q[k]-v)*t));}}return out;}
 function emit(p,low){for(let i=1;i+1<p.length;i++)roof.tri(...[p[0],p[i],p[i+1]].map(q=>[q[0],low?q[3]:q[1],q[2]]));}
 if(!overlap){emit(packed,false);return;}emit(half(packed,1),false);emit(half(packed,-1),true);
}
for(let i=0;i<joinXs.length-1;i++)for(let j=0;j<seamT.length-1;j++){const x=joinXs[i],xx=joinXs[i+1],t=seamT[j],u=seamT[j+1],a=[x,at(north(x),join(x),t)],c=[x,at(north(x),join(x),u)],d=[xx,at(north(xx),join(xx),u)],e=[xx,at(north(xx),join(xx),t)],overlap=x>=W-1e-8&&t>=.5-1e-8;if(overlap&&t===.5&&Math.min(highY(...a),highY(...e))<5.5)throw Error('transverse roof does not cover wing ridge at overlap limit');envelope([a,c,d],overlap);envelope([a,d,e],overlap);}
const wingXs=joinXs.filter(x=>x>=W-1e-8);for(let i=0;i<wingXs.length-1;i++){const x=wingXs[i],xx=wingXs[i+1];roof.quad([x,lowY(x),join(x)],[x,lowY(x),S],[xx,lowY(xx),S],[xx,lowY(xx),join(xx)]);
 // High/low closure only where high roof eave stands above low wing.
 const a=[x,lowY(x),highY(x,join(x)),join(x)],q=[xx,lowY(xx),highY(xx,join(xx)),join(xx)];let ps=[a,q];if((a[2]>=a[1])!==(q[2]>=q[1])){const t=(a[2]-a[1])/((a[2]-a[1])-(q[2]-q[1])),r=a.map((v,k)=>v+(q[k]-v)*t);ps=a[2]>=a[1]?[a,r]:[r,q];}if(ps.every(p=>p[2]>=p[1]-1e-9)){const [p,r]=ps;junction.quad([p[0],p[1],p[3]],[r[0],r[1],r[3]],[r[0],r[2],r[3]],[p[0],p[2],p[3]]);}}
// Photo-visible projecting south coping and eave lip have real top/underside.
for(let i=0;i<wingXs.length-1;i++){const x=wingXs[i],xx=wingXs[i+1],a=lowY(x),q=lowY(xx);trimRoof.quad([x,a,S],[x,a,S+.20],[xx,q,S+.20],[xx,q,S]);trimRoof.quad([x,a-.12,S+.20],[x,a-.12,S],[xx,q-.12,S],[xx,q-.12,S+.20]);trimRoof.quad([x,a-.12,S+.20],[xx,q-.12,S+.20],[xx,q,S+.20],[x,a,S+.20]);}
for(const side of[-1,1]){const x=side<0?W:E,outer=x+side*.18,z=join(x),back=join(outer);const ps=[[x,3.3,z],[x,3.3,S+.2],[outer,3.35,S+.2],[outer,3.35,back]];if(side<0)ps.reverse();trimRoof.quad(...ps);const fascia=[[outer,3.23,back],[outer,3.23,S+.2],[outer,3.35,S+.2],[outer,3.35,back]];if(side>0)fascia.reverse();trimRoof.quad(...fascia);trimRoof.quad(...ps.map(p=>[p[0],p[1]-.12,p[2]]).reverse());const backCap=[[x,3.18,z],[outer,3.23,back],[outer,3.35,back],[x,3.3,z]];if(side>0)backCap.reverse();trimRoof.quad(...backCap);const endCap=[[x,3.18,S+.2],[outer,3.23,S+.2],[outer,3.35,S+.2],[x,3.3,S+.2]];if(side<0)endCap.reverse();trimRoof.quad(...endCap);}
for(let z=join(C)+.10;z<S+.17;z+=.19)for(let side of[-1,1])for(let j=0;j<30;j++){const x=C+side*2.5*j/30,xx=C+side*2.5*(j+1)/30,ps=[[x,lowY(x)+.014,z-.035],[xx,lowY(xx)+.014,z-.035],[xx,lowY(xx)+.04,z+.035],[x,lowY(x)+.04,z+.035]];if(side>0)ps.reverse();rolls.quad(...ps);}
mesh('roof-step-closure',junction,color.brick,30);mesh('projecting-eave',trimRoof,color.roof,19);
const sill=1.05,spring=2.43,half=.625,arch=x=>spring+.22*Math.sqrt(Math.max(0,1-((x-C)/half)**2));
const xs=Array.from(new Set([...Array.from({length:101},(_,i)=>W+(E-W)*i/100),C-half,C+half])).sort((a,b)=>a-b);for(let i=0;i<xs.length-1;i++){let x=xs[i],xx=xs[i+1],m=(x+xx)/2,has=Math.abs(m-C)<half;
 if(!has)front.quad([x,.08,S],[xx,.08,S],[xx,roofY(xx,S),S],[x,roofY(x,S),S]);else{front.quad([x,.08,S],[xx,.08,S],[xx,sill,S],[x,sill,S]);front.quad([x,arch(x),S],[xx,arch(xx),S],[xx,roofY(xx,S),S],[x,roofY(x,S),S]);reveal.quad([x,arch(x),S],[x,arch(x),S-.20],[xx,arch(xx),S-.20],[xx,arch(xx),S]);glass.quad([x,sill,S-.18],[xx,sill,S-.18],[xx,arch(xx),S-.18],[x,arch(x),S-.18]);}}
for(const x of[C-half,C+half]){const ps=[[x,sill,S],[x,sill,S-.2],[x,spring,S-.2],[x,spring,S]];if(x>C)ps.reverse();reveal.quad(...ps);}reveal.quad([C-half,sill,S],[C+half,sill,S],[C+half,sill,S-.2],[C-half,sill,S-.2]);
mesh('shell',body,color.brick,30);mesh('south-gable',front,color.brick,30);mesh('window-reveals',reveal,color.brick,30);mesh('window-glass',glass,'#485b50',28);mesh('roof',roof,color.roof,19);mesh('tile-rolls',rolls,'#747c71',19);
const named=b.e.add;b.e.add=function(k,...args){return named.call(this,'400-wing102-joinery-'+k,...args)};try{for(const x of[C-half+.03,C,C+half-.03])b.box(x,(sill+spring)/2,S-.08,.065,spring-sill,.09,color.red,38);b.box(C,sill+.025,S-.08,half*2,.05,.09,color.red,38);for(let i=0;i<32;i++){let x=C-half+2*half*i/32,xx=C-half+2*half*(i+1)/32;b.beam([x,arch(x)-.025,S-.08],[xx,arch(xx)-.025,S-.08],.06,color.red,38);}b.box(C,sill-.06,S+.01,half*2+.18,.12,.34,'#b8b8a8',24);}finally{b.e.add=named;}
const copingAdd=b.e.add;b.e.add=function(k,...args){return copingAdd.call(this,'400-wing102-coping-'+k,...args)};try{for(let i=0;i<60;i++){const x=W+(E-W)*i/60,xx=W+(E-W)*(i+1)/60;b.beam([x,lowY(x)+.085,S+.15],[xx,lowY(xx)+.085,S+.15],.14,'#747c71',19);b.beam([x,lowY(x)-.32,S+.075],[xx,lowY(xx)-.32,S+.075],.085,color.brick,30);}for(let x=W+.08;x<E-.04;x+=.15)b.beam([x,lowY(x)-.045,S-.02],[x,lowY(x)-.045,S+.22],.085,'#747c71',19);}finally{b.e.add=copingAdd;}
// Individually jointed gray voussoirs follow the photographed shallow arch.
const ring=new G.Geometry();for(let i=0;i<26;i++){const t=Math.PI*i/26+.009,u=Math.PI*(i+1)/26-.009,pt=(a,r,z)=>{const nx=Math.cos(a)/half,ny=Math.sin(a)/.22,l=Math.hypot(nx,ny),d=r-half;return[C+half*Math.cos(a)+d*nx/l,spring+.22*Math.sin(a)+d*ny/l,z];},a=pt(t,half,S+.045),q=pt(u,half,S+.045),d=pt(u,half+.16,S+.045),e=pt(t,half+.16,S+.045);ring.quad(a,e,d,q);ring.quad(d,e,[e[0],e[1],S],[d[0],d[1],S]);ring.quad(q,d,[d[0],d[1],S],[q[0],q[1],S]);ring.quad(e,a,[a[0],a[1],S],[e[0],e[1],S]);}mesh('arch-brick-ring',ring,'#afb0a1',30);
const rubble=color.stone.map(()=>new G.Geometry());for(const [a,c,lo,hi]of[[W+.30,E-.30,.32,.82],[W+.30,C-half-.18,1.06,2.82],[C+half+.18,E-.30,1.06,2.82]])for(const cell of Y.Building401.rubbleCells(0,(c-a)*1.8,1020+Math.round(a*100),0,(hi-lo)*1.8)){let g=rubble[cell.id%4],p=cell.poly.map(q=>[a+q[0]/1.8,lo+q[1]/1.8]),cx=p.reduce((s,a)=>s+a[0],0)/p.length,cy=p.reduce((s,a)=>s+a[1],0)/p.length;for(let i=0;i<p.length;i++){let a=p[i],q=p[(i+1)%p.length];g.tri([cx,cy,S+.032],[a[0],a[1],S+.02],[q[0],q[1],S+.02]);}}
rubble.forEach((g,i)=>mesh('south-rubble-'+i,g,color.stone[i],24));b.id=oldId;
return{...ret,detail:'math400-wing102-private',northJunctionVerified:false,eastWingUnresolved:true,retainedHouseGeometry:false,sourceOutline:false,scope:'South east wing added; existing east cross-wing shell trimmed and joined with inferred northern roof. Gate and neighbor retained.',eastWingFit:{west:W,east:E,south:S,eave:3.3,ridge:5.5,registration:'photo-fit, metre-scale uncertainty'},wholeHouseHeightChanged:false};};Y.Math400Wing102={cut,west:W,east:E,south:S,northJunctionVerified:false};})(YY);
