/* No.54: the documented west entrance, fitted to its recessed mapped west edge.
 * Keep the inherited roof and all non-entry detail; its overall typology remains approximate. */
(function(Y){'use strict';const A=Y.Architecture30,previous=A.render,G=Y.Geo,M=Y.M,ID='way/866277599',PICK=264;
const edge=[[-52.609,365.714],[-52.455,377.195]],length=Math.hypot(edge[1][0]-edge[0][0],edge[1][1]-edge[0][1]),u=[(edge[1][0]-edge[0][0])/length,(edge[1][1]-edge[0][1])/length],n=[-u[1],u[0]],angle=Math.atan2(n[0],n[1]),centre=2.25,gap=1.85,spring=2.85,rise=.925,threshold=.45,depth=.32;
function roofAt(records,x,z){let y=-Infinity;for(const o of records){if(o.p[0]!==19)continue;for(let i=0;i<o.g.v.length;i+=24){const q=[0,8,16].map(k=>M.apply(o.m,[o.g.v[i+k],o.g.v[i+k+1],o.g.v[i+k+2],1])),[a,b,c]=q,den=(b[2]-c[2])*(a[0]-c[0])+(c[0]-b[0])*(a[2]-c[2]);if(Math.abs(den)<1e-10)continue;const s=((b[2]-c[2])*(x-c[0])+(c[0]-b[0])*(z-c[2]))/den,t=((c[2]-a[2])*(x-c[0])+(a[0]-c[0])*(z-c[2]))/den;if(s>=-1e-5&&t>=-1e-5&&s+t<=1+1e-5)y=Math.max(y,s*a[1]+t*b[1]+(1-s-t)*c[1]);}}return y;}
function wall(records){const g=new G.Geometry(),start=centre-gap/2,end=centre+gap/2,ts=[0,start,end,10.261];for(let t=.20;t<10.261;t+=.20)ts.push(t);for(let i=0;i<=32;i++)ts.push(centre-Math.cos(i*Math.PI/32)*gap/2);ts.sort((a,b)=>a-b);const unique=ts.filter((t,i)=>!i||t-ts[i-1]>1e-7),top=t=>{const x=edge[0][0]+u[0]*t-n[0]*.00001,z=edge[0][1]+u[1]*t-n[1]*.00001;return roofAt(records,x,z);},low=t=>t>=start-1e-7&&t<=end+1e-7?spring+rise*Math.sqrt(Math.max(0,1-((t-centre)/(gap/2))**2)):.045;
for(let i=0;i<unique.length-1;i++){const a=unique[i],b=unique[i+1],inside=(a+b)/2>start&&(a+b)/2<end,la=inside?low(a):.045,lb=inside?low(b):.045,ha=top(a),hb=top(b);if(!Number.isFinite(ha)||!Number.isFinite(hb))throw Error('No.54 west wall has no supporting roof');g.quad([a,la,0],[b,lb,0],[b,hb,0],[a,ha,0]);g.quad([b,lb,-depth],[a,la,-depth],[a,ha,-depth],[b,hb,-depth]);g.quad([a,ha,0],[b,hb,0],[b,hb,-depth],[a,ha,-depth]);g.quad([a,la,-depth],[b,lb,-depth],[b,lb,0],[a,la,0]);}
for(const t of[0,10.261]){const h=top(t),q=[[t,.045,0],[t,h,0],[t,h,-depth],[t,.045,-depth]];if(t===0)q.reverse();g.quad(...q);}
for(const t of[start,end]){const q=[[t,.045,0],[t,spring,0],[t,spring,-depth],[t,.045,-depth]];if(t===start)q.reverse();g.quad(...q);}return g;}
// Clip a mapped edge against the original body's horizontal cap, so eaves outside
// the body do not become new walls. The cap is already clipped to the footprint.
function capIntervals(records,a,b){const intervals=[];for(const o of records){if(o.c!=='#a4a49b')continue;for(let i=0;i<o.g.v.length;i+=24){if(o.g.v[i+4]<.99||o.g.v[i+1]<5)continue;const tri=[0,8,16].map(k=>M.apply(o.m,[o.g.v[i+k],o.g.v[i+k+1],o.g.v[i+k+2],1])),sign=Math.sign((tri[1][0]-tri[0][0])*(tri[2][2]-tri[0][2])-(tri[1][2]-tri[0][2])*(tri[2][0]-tri[0][0]));let lo=0,hi=1;for(let j=0;j<3;j++){const p=tri[j],q=tri[(j+1)%3],side=x=>sign*((q[0]-p[0])*(x[1]-p[2])-(q[2]-p[2])*(x[0]-p[0])),s=side(a),e=side(b),d=e-s;if(Math.abs(d)<1e-10){if(s<-.00001){lo=2;break;}}else if(d>0)lo=Math.max(lo,-s/d);else hi=Math.min(hi,-s/d);}if(hi-lo>1e-6)intervals.push([Math.max(0,lo),Math.min(1,hi)]);}}
intervals.sort((a,b)=>a[0]-b[0]);const out=[];for(const v of intervals){const last=out[out.length-1];if(last&&v[0]<=last[1]+1e-5)last[1]=Math.max(last[1],v[1]);else out.push(v);}return out;}
function remainingCuts(b,records,f){const g=new G.Geometry(),ring=f.geometry.coordinates[0];for(const index of[4,5,7,8]){const a=ring[index],c=ring[index+1],dx=c[0]-a[0],dz=c[1]-a[1],len=Math.hypot(dx,dz),nx=-dz/len,nz=dx/len,at=(t,y,back=0)=>[a[0]+dx*t-nx*back,y,a[1]+dz*t-nz*back];for(const[lo,hi]of capIntervals(records,a,c)){const count=Math.ceil((hi-lo)*len/.20),top=t=>roofAt(records,a[0]+dx*t-nx*.00001,a[1]+dz*t-nz*.00001);for(let j=0;j<count;j++){const s=lo+(hi-lo)*j/count,e=lo+(hi-lo)*(j+1)/count,hs=top(s),he=top(e);if(!Number.isFinite(hs)||!Number.isFinite(he))throw Error('No.54 cut wall has no roof');g.quad(at(s,.045),at(e,.045),at(e,he),at(s,hs));g.quad(at(e,.045,depth),at(s,.045,depth),at(s,hs,depth),at(e,he,depth));g.quad(at(s,hs),at(e,he),at(e,he,depth),at(s,hs,depth));g.quad(at(e,.045),at(s,.045),at(s,.045,depth),at(e,.045,depth));}for(const t of[lo,hi]){const q=[at(t,.045),at(t,top(t)),at(t,top(t),depth),at(t,.045,depth)];if(t===lo)q.reverse();g.quad(...q);}}}
b.e.add('yannan264-other-cut-walls',g,M.identity(),'#a4a49b',[18,PICK,0,.6]);}
function grilleScrolls(paths){const g=new G.Geometry(),half=.008,front=-.172,back=-.197;for(const path of paths)for(let i=0;i<path.length-1;i++){const a=path[i],b=path[i+1],dx=b[0]-a[0],dy=b[1]-a[1],len=Math.hypot(dx,dy);if(len<1e-8)continue;const nx=-dy/len*half,ny=dx/len*half,p=[a[0]+nx,a[1]+ny],q=[b[0]+nx,b[1]+ny],r=[b[0]-nx,b[1]-ny],s=[a[0]-nx,a[1]-ny],v=(p,z)=>[p[0],p[1],z];g.quad(v(p,front),v(q,front),v(r,front),v(s,front));g.quad(v(s,back),v(r,back),v(q,back),v(p,back));g.quad(v(p,back),v(q,back),v(q,front),v(p,front));g.quad(v(r,back),v(s,back),v(s,front),v(r,front));}for(let i=0;i<g.v.length;i+=24){const a=g.v.slice(i,i+8),c=g.v.slice(i+16,i+24);for(let j=0;j<8;j++){g.v[i+j]=c[j];g.v[i+16+j]=a[j];}for(let k=0;k<24;k+=8)for(let j=3;j<6;j++)g.v[i+k+j]*=-1;}return g;}

function entrance(b,records){const before=[b.id,b.origin,b.rotation];b.id=PICK;b.origin=[0,0,0];b.rotation=0;try{b.local(edge[0][0],0,edge[0][1],angle,()=>{
 b.mesh('yannan264-west-closure',wall(records),0,0,0,1,1,1,'#a4a49b',18,.6);
 const ret=new G.Geometry(),a=[-4.246,.045,0],c=[0,.045,0],roofA=roofAt(records,-56.855,365.771),roofC=roofAt(records,edge[0][0]+.002,edge[0][1]);
 ret.quad(a,c,[0,roofC,0],[-4.246,roofA,0]);ret.quad([0,.045,-depth],[-4.246,.045,-depth],[-4.246,roofA,-depth],[0,roofC,-depth]);ret.quad([-4.246,roofA,0],[0,roofC,0],[0,roofC,-depth],[-4.246,roofA,-depth]);
 // Return is rotated from the west face onto the north-block recess shoulder.
 b.local(0,0,0,Math.PI/2,()=>b.mesh('yannan264-north-return',ret,0,0,0,1,1,1,'#a4a49b',18,.6));
 // Stone access: three joined treads reach the actual door threshold.
 for(let i=0;i<3;i++)b.box(centre,(i+1)*.15/2,.78-i*.30,gap,.15*(i+1),.36,'#b3b4a9',10,.2);
 b.box(centre,threshold/2,-.015,gap,threshold,.63,'#b3b4a9',10,.2);
 const z=-.22,w=1.45,h=2.45,green='#526861';
 for(const side of[-1,1])b.box(centre+side*(gap+w)/4,threshold+h/2,-.28,(gap-w)/2,h,.12,'#858b82',18,.7);
 const head=new G.Geometry(),trim=new G.Geometry(),joints=new G.Geometry();for(let i=0;i<32;i++){const a=i*Math.PI/32,c=(i+1)*Math.PI/32,x=t=>centre-Math.cos(t)*gap/2,y=t=>Math.max(threshold+h,spring+Math.sin(t)*rise);head.quad([x(a),threshold+h,-.28],[x(c),threshold+h,-.28],[x(c),y(c),-.28],[x(a),y(a),-.28]);const at=(t,k)=>[centre-Math.cos(t)*(gap/2+k),spring+Math.sin(t)*(rise+k),.014];trim.quad(at(a,0),at(c,0),at(c,.25),at(a,.25));if(i%2===0){const lo=a+.008,hi=a+.018,p=(t,k)=>[centre-Math.cos(t)*(gap/2+k),spring+Math.sin(t)*(rise+k),.018];joints.quad(p(lo,0),p(hi,0),p(hi,.25),p(lo,.25));}}
 b.mesh('yannan264-recessed-head',head,0,0,0,1,1,1,'#858b82',18,.7);b.mesh('yannan264-brick-arch-ring',trim,0,0,0,1,1,1,'#a9aa9e',18,.82);b.mesh('yannan264-radial-mortar',joints,0,0,0,1,1,1,'#666d66',18,.84);
 for(const x of[centre-w/2,centre+w/2])b.box(x,threshold+h/2,z,.075,h,.10,green,12,.9);
 for(const y of[threshold+.035,threshold+1.35,threshold+h-.035])b.box(centre,y,z,w,.07,.10,green,12,.9);
 // Unequal metal leaves: solid lower panels, open upper grille over dark glazing.
 const paths=[],split=centre-.36;for(const [a,c]of[[centre-w/2,split],[split,centre+w/2]]){const ww=c-a,xx=(a+c)/2;b.box(xx,threshold+.68,z,ww-.07,1.27,.07,green,12,.9);b.box(xx,threshold+1.90,z-.04,ww-.08,1.03,.028,'#394a49',5,.8);for(let t=a+.11;t<c-.05;t+=.15){b.box(t,threshold+1.90,z+.03,.014,1.03,.025,green,12,.95);const stem=[];for(let k=0;k<=40;k++){const q=k/40;stem.push([t+.044*Math.sin(q*Math.PI*2),threshold+1.43+q*.94]);}paths.push(stem);for(const sy of[-1,1]){const loop=[];for(let k=0;k<=24;k++){const q=k/24*Math.PI*2;loop.push([t+.026*Math.cos(q),threshold+1.90+sy*.44+.027*Math.sin(q)]);}paths.push(loop);}}}
 b.mesh('yannan264-iron-scrolls',grilleScrolls(paths),0,0,0,1,1,1,green,12,.96);
 b.box(split,threshold+h/2,z+.01,.055,h,.10,green,12,.95);
 b.heritagePlaque('54',centre+gap/2+.38,1.73,.06,.42,.31);
 });}finally{[b.id,b.origin,b.rotation]=before;}}
A.render=function(b,f,add){if(f.properties.id!==ID||f.properties.pickId!==PICK)return previous.call(this,b,f,add);const original=b.historicVilla,own=Object.prototype.hasOwnProperty.call(b,'historicVilla'),records=[],eadd=b.e.add;
b.historicVilla=function(p,w,d){const door=this.heritageDoor,plaque=this.heritagePlaque,box=this.box,keys=['heritageDoor','heritagePlaque','box'],owned=keys.map(k=>Object.prototype.hasOwnProperty.call(this,k));this.heritageDoor=function(){};this.heritagePlaque=function(){};this.box=function(x,y,z,ww,h,dd,...rest){if(x===0&&y===.19&&ww===1.25&&h===.065)return;return box.call(this,x,y,z,ww,h,dd,...rest);};try{return original.call(this,p,w,d);}finally{keys.forEach((k,i)=>{if(owned[i])this[k]=[door,plaque,box][i];else delete this[k];});}};
b.e.add=function(k,g,m,c,p,uv){records.push({k,g,m:new Float32Array(m),c,p,uv});return eadd.call(this,k,g,m,c,p,uv);};let result;try{result=previous.call(this,b,f,add);}finally{b.e.add=eadd;if(own)b.historicVilla=original;else delete b.historicVilla;}entrance(b,records);remainingCuts(b,records,f);return result;};Y.Yannan264Details={id:ID,pickId:PICK,edge,u,n,angle,length,centre,gap,spring,rise,threshold,depth};
})(YY);
