const assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
const src=path.join(__dirname,'../src');
function env(protocol='https:',fail=false,incomplete=false){let requests=[];const YY={BUILDER_DATA318:[{key:'WestGateLionSource318',file:'lion.js'},{key:'Office105Dragons318',file:'office.js'}]};const document={currentScript:{src:protocol+'//example.test/site/assets/app.js'},baseURI:protocol+'//example.test/site/index.html',createElement:()=>({remove(){}}),head:{append(s){requests.push(s.src);queueMicrotask(()=>{if(fail){s.onerror();return;}if(!incomplete)YY[s.src.endsWith('lion.js')?'WestGateLionSource318':'Office105Dragons318']={exact:true};s.onload();});}}};vm.runInNewContext(fs.readFileSync(path.join(src,'builder-data318-loader.js'),'utf8'),{YY,document,URL});return {YY,requests,setFail(v){fail=v},setIncomplete(v){incomplete=v}};}
(async()=>{
 for(const protocol of ['https:','file:']){const e=env(protocol);assert.equal(e.requests.length,0);const p=e.YY.loadBuilderData318();assert.equal(e.YY.loadBuilderData318(),p);await p;assert.deepEqual(e.requests,[protocol+'//example.test/site/assets/lion.js',protocol+'//example.test/site/assets/office.js']);await e.YY.loadBuilderData318();assert.equal(e.requests.length,2);}
 for(const incomplete of [false,true]){const e=env('https:',!incomplete,incomplete);await assert.rejects(e.YY.loadBuilderData318());e.setFail(false);e.setIncomplete(false);await e.YY.loadBuilderData318();assert(e.YY.Office105Dragons318);}
 const app=fs.readFileSync(path.join(src,'app-v29.js'),'utf8');const block=app.slice(app.indexOf('async function loadRenderResources('),app.indexOf('async function init('));
 for(const cached of [true,false]){let calls=[];const e=env();e.YY.SceneCache46=cached?{load:async()=>{calls.push('cache');return'cached'}}:null;e.YY.SCENE_PACKAGE46=cached?{}:null;e.YY.createMetricCampus=()=>{assert(e.YY.WestGateLionSource318&&e.YY.Office105Dragons318);calls.push('live');return'live'};const ctx={Y:e.YY};vm.createContext(ctx);vm.runInContext(block,ctx);assert.equal(await ctx.loadRenderResources({loadMaterials:async()=>{},loadScan1119:async()=>{},finishPrograms(){}},()=>{}),cached?'cached':'live');assert.equal(e.requests.length,cached?0:2);await ctx.loadRenderResources({loadMaterials:async()=>{},loadScan1119:async()=>{}},()=>{});assert.equal(e.requests.length,cached?0:2);}
 // Cache rejection preserves existing rejection policy; never silently live-builds.
 const e=env();e.YY.SceneCache46={load:async()=>{throw Error('cache fail')}};e.YY.SCENE_PACKAGE46={};e.YY.createMetricCampus=()=>{throw Error('must not run')};const ctx={Y:e.YY};vm.createContext(ctx);vm.runInContext(block,ctx);await assert.rejects(ctx.loadRenderResources({loadMaterials:async()=>{},loadScan1119:async()=>{}},()=>{}),/cache fail/);assert.equal(e.requests.length,0);
 console.log('PASS: HTTP/file URLs, no eager load, concurrent once, failure/incomplete retry, cached/live/recovery and cache rejection');
})().catch(e=>{console.error(e);process.exitCode=1});
