const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const APP=path.resolve(__dirname,'..');
function capture(candidate,pick){
 fs.writeSync(2,'ceramic162 capture '+pick+' '+(candidate?'candidate':'original')+' start\n');
 const ctx=vm.createContext({console,document:{createElement:()=>({getContext:()=>new Proxy({measureText:s=>({width:s.length*20})},{get:(o,k)=>o[k]||(()=>{})})})}});vm.runInContext('var YY={}',ctx);
 for(const m of fs.readFileSync(APP+'/index.html','utf8').matchAll(/script src="src\/(.*?)\.js"/g)){const name=m[1];if(name==='scene-v29')break;let source=fs.readFileSync(APP+'/src/'+name+'.js','utf8');if(name==='ceramic-uv162'&&!candidate)continue;vm.runInContext(source,ctx,{filename:name});}
 const Y=ctx.YY,f=Y.CAMPUS.features.find(f=>f.properties.pickId===pick),e=Object.create(Y.Engine.prototype),out=[];e.buckets=new Map();e.stats={instances:0};
 const b=new Y.Builder({add(k,g,m,c,p,uv){Y.Engine.prototype.add.call(e,k,g,m,c,p,uv);const bucket=e.buckets.get(k),vertices=Buffer.from(bucket.geometry.v.buffer),generated=Buffer.from(new Float32Array(g.v).buffer);assert.ok(vertices.equals(generated),'same key cannot change cached geometry '+k);out.push({key:k,vertices,instance:Buffer.from(new Float32Array(bucket.instances.slice(-28)).buffer)});}});
 const run=()=>Y.Landscape42.withElevation(b,f,()=>Y.Architecture30.render(b,f,(k,g,c,mat,id)=>b.e.add(k,g,Y.M.identity(),c,[mat,id,0,0])));run();const first=out.slice();out.length=0;if(pick!==403&&pick!==96){fs.writeSync(2,'ceramic162 capture '+pick+' '+(candidate?'candidate':'original')+' done\n');return first;}run();assert.equal(out.length,first.length);for(let i=0;i<out.length;i++){assert.equal(out[i].key,first[i].key);assert.ok(out[i].vertices.equals(first[i].vertices));assert.ok(out[i].instance.equals(first[i].instance));}fs.writeSync(2,'ceramic162 capture '+pick+' '+(candidate?'candidate':'original')+' done\n');return first;
}
function distinct(v,fields){const seen=new Set();for(let i=0;i<v.length;i+=32)seen.add(v.subarray(i,i+fields*4).toString('hex'));return seen.size;}
const allowed=new Set(['400-wing102-retained-math42-continuous-roof-400','math42-continuous-roof-401','math42-continuous-roof-402','math42-continuous-roof-403','v30-clipped-96-pagoda-#b0aa95|25|0']);
for(const pick of[96,400,401,402,403])test('real building '+pick+' keeps every live vertex bit, primitive order, instance and nonceramic UV; repeated small-case cache is stable',()=>{const old=capture(false,pick),fresh=capture(true,pick),changed=[];assert.equal(old.length,fresh.length);for(let i=0;i<old.length;i++){const a=old[i],b=fresh[i];assert.equal(a.key,b.key);assert.ok(a.instance.equals(b.instance));assert.equal(a.vertices.length,b.vertices.length);if(a.vertices.equals(b.vertices))continue;assert.ok(allowed.has(a.key),'unexpected geometry changed '+a.key);assert.equal(b.instance.readFloatLE(80),25);for(let j=0;j<a.vertices.length;j+=32)assert.ok(a.vertices.subarray(j,j+24).equals(b.vertices.subarray(j,j+24)),'position/normal or triangle order changed '+a.key);const before=distinct(a.vertices,8),after=distinct(b.vertices,8);assert.ok(after<before,'actual indexed reuse must improve');changed.push({key:a.key,triangles:a.vertices.length/96,before,after,rawHash:crypto.createHash('sha256').update(b.vertices).digest('hex')});}assert.equal(changed.length,1);console.log(JSON.stringify({pick,changed}));});
test('untargeted ceramic and other materials keep complete geometry and instance records',()=>{for(const pick of[115,165]){const old=capture(false,pick),fresh=capture(true,pick);assert.deepEqual(fresh,old);}});
test('mat25 producers stay explicit; position or normal one-bit differences are never treated as reusable vertices',()=>{for(const field of[0,3]){const vertices=Buffer.alloc(64);vertices.writeUInt32LE(1,32+field*4);assert.equal(distinct(vertices,6),2);}const vertices=Buffer.alloc(64);vertices.writeFloatLE(1,32+24);assert.equal(distinct(vertices,8),2);assert.equal(distinct(vertices,6),1);});

test('final-key gate preserves other materials, rejects mixed consumers and restores own/inherited emitters on success and failure',()=>{
 const source=fs.readFileSync(APP+'/src/ceramic-uv162.js','utf8'),key='math42-continuous-roof-402';
 for(const own of[false,true])for(const kind of['success','mixed','throw']){
  const g={v:[1,2,3,0,1,0,.2,.8],detailWidth:.125},records=[],emit=function(...a){records.push(a);if(kind==='throw')throw Error('forced');},e=own?{add:emit}:Object.create({add:emit}),b={e};
  const Y={Geo:{Geometry:class{constructor(){this.v=[]}}},Architecture30:{render(builder){builder.e.add('different-key',g,[],null,[31]);builder.e.add(key,g,[],null,[kind==='mixed'?31:25]);return'ok';}}};vm.runInNewContext(source,{YY:Y});
  if(kind==='success'){assert.equal(Y.Architecture30.render(b,{properties:{pickId:402}}),'ok');assert.equal(records[0][1],g);assert.deepEqual(Array.from(records[1][1].v),[1,2,3,0,1,0,1,3]);assert.equal(records[1][1].detailWidth,.125);assert.deepEqual(g.v,[1,2,3,0,1,0,.2,.8]);}else assert.throws(()=>Y.Architecture30.render(b,{properties:{pickId:402}}),kind==='mixed'?/requires material25/:/forced/);
  assert.equal(e.add,emit);assert.equal(Object.hasOwn(e,'add'),own);
 }
});
