const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
function fixture(deferred){
 const Y={},ctx=vm.createContext({YY:Y});for(const n of ['math','visibility','engine'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../src/'+n+'.js'),'utf8'),ctx);
 let serial=0,vao=null,array=null;const events=[],gl={ARRAY_BUFFER:1,ELEMENT_ARRAY_BUFFER:2,FLOAT:3,DYNAMIC_DRAW:4,TRIANGLES:5,UNSIGNED_SHORT:6,UNSIGNED_INT:7,
 createBuffer(){return{id:++serial};},createVertexArray(){const v={id:++serial,a:{}};events.push(['create',v.id]);return v;},bindVertexArray(v){vao=v;},bindBuffer(t,b){if(t===1)array=b;else if(vao)vao.index=b;},enableVertexAttribArray(){},vertexAttribDivisor(){},vertexAttribPointer(a,n,t,norm,stride,offset){vao.a[a]={buffer:array,offset,stride};events.push(['pointer',a]);},bufferData(t,size){array.bytes=new Uint8Array(size);events.push(['upload']);},bufferSubData(t,o,data,start,len){array.bytes.set(new Uint8Array(data.buffer,data.byteOffset+start*4,len*4),o);},deleteVertexArray(v){if(v)events.push(['delete',v.id]);},deleteBuffer(){},deleteTexture(){},deleteProgram(){},useProgram(){},enable(){},disable(){},depthMask(){},blendFunc(){},drawElementsInstanced(mode,count,type,offset,instances){trace.push({count,type,offset,instances,a:Object.fromEntries(Object.entries(vao.a).map(([k,v])=>[k,{offset:v.offset,stride:v.stride,buffer:v.buffer.name||'stream'}])),index:vao.index.name});},drawArraysInstanced(mode,first,count,instances){trace.push({first,count,instances});}};
 const trace=[],e=Object.assign(Object.create(Y.Engine.prototype),{gl,state:{deferredInstanceVAO:deferred,selected:0,isolate:0,explode:0,detailLOD:true,meshCulling:true,vegetation:true,routeEdges:new Set(),specializedCeramic:false,specializedFoliage:false,skyAfterOpaque:false},camera:{eye:[0,0,10],fov:.8},canvas:{clientHeight:1000},buckets:new Map(),visibilityCaches:new Map(),stats:{visibilityBuilds:0,instanceUploadBytes:0},reflectTarget:{w:100,h:100,tex:{}},shadowTarget:{tex:{}},main:{p:1},glass:{p:2},meshResources:[],uniform(){},sampler(){},stateUniforms(){},disposeTarget(){}});
 const resource={vertexBuffer:{name:'vertices'},indexBuffer:{name:'indices'},indexType:'uint16'};
 for(let i=0;i<5;i++){const data=new Float32Array(28);data.set(Y.M.identity());data[20]=i===4?44:24;data[21]=i+1;data.set([0,0,1,1],24);const b={resource,vertexCount:6,data,count:1,spatial:new Float32Array([0,0,0,1,1]),passes:new Map()};Y.Visibility.compile(b);e.buckets.set('b'+i,b);}
 const ranged=e.buckets.get('b3');e.visibleRanges=b=>b===ranged?[[0,3]]:null;e.reflectionPlanes=vp=>Y.M.frustum(vp);return{e,Y,events,trace,vp:Y.M.identity()};
}
function snapshot(f,slot){f.trace.length=0;const c=f.e.visibleScene(f.vp,slot);f.e.draw(f.e.main,f.vp,f.e.camera.eye,slot===0?0:slot);return{trace:f.trace.slice(),stream:Array.from(f.e.instanceStreams.get(slot).data.slice(0,f.e.instanceStreams.get(slot).used)),items:Array.from(c.items,x=>({count:x.record.count,offset:x.record.offset})),heads:Array.from(c.drawItems,x=>({count:x.record.count,offset:x.record.offset,ranges:x.ranges&&Array.from(x.ranges,r=>Array.from(r))}))};}
test('actual visibility and draw preserve ordered bytes, attributes, ranges, transparent draws across passes and changing heads',()=>{const a=fixture(false),b=fixture(true);for(const slot of [0,3,2]){assert.deepEqual(snapshot(b,slot),snapshot(a,slot));const count=b.events.length;assert.deepEqual(snapshot(b,slot),snapshot(a,slot));assert.equal(b.events.length,count,'cache hit emits no pointer updates or upload');}
 for(const f of[a,b]){f.e.buckets.get('b0').spatial[0]=100;f.e.visibilityCaches.clear();}assert.deepEqual(snapshot(b,0),snapshot(a,0));assert(b.events.filter(x=>x[0]==='pointer').length<a.events.filter(x=>x[0]==='pointer').length);
});
test('external instanceCache remains immediate and growth retains exact bytes; feature toggle invalidates cache',()=>{const f=fixture(true),b=f.e.buckets.get('b0'),stream={buffer:f.e.gl.createBuffer(),data:new Float32Array(1),used:0};const r=f.e.instanceCache(b,9,1,stream,b.data);assert(r.vao);assert.equal(r.count,1);assert.deepEqual(Array.from(stream.data.slice(0,28)),Array.from(b.data));const first=f.e.visibleScene(f.vp,0);f.e.state.deferredInstanceVAO=false;assert.notEqual(f.e.visibleScene(f.vp,0),first);});
test('dispose deletes only materialized VAOs once and fresh prepared context uses new records',()=>{const f=fixture(true);snapshot(f,0);const created=f.events.filter(x=>x[0]==='create').map(x=>x[1]);f.e.dispose();assert.deepEqual(f.events.filter(x=>x[0]==='delete').map(x=>x[1]),created);assert.equal(new Set(created).size,created.length);const fresh=fixture(true);assert.deepEqual(snapshot(fresh,0),snapshot(fixture(false),0));});
test('selected displacement, empty visibility, isolation and head return preserve every pass',()=>{const a=fixture(false),b=fixture(true);for(const state of [{selected:2,explode:3},{selected:0,explode:0,isolate:2},{isolate:999},{isolate:0}]){for(const f of[a,b]){Object.assign(f.e.state,state);f.e.visibilityCaches.clear();}for(const slot of[0,3,2])assert.deepEqual(snapshot(b,slot),snapshot(a,slot));}for(const f of[a,b]){f.e.buckets.get('b0').spatial[0]=100;f.e.visibilityCaches.clear();}snapshot(a,0);snapshot(b,0);for(const f of[a,b]){f.e.buckets.get('b0').spatial[0]=0;f.e.visibilityCaches.clear();}assert.deepEqual(snapshot(b,0),snapshot(a,0));});
test('deferred pointers finish before the single upload and bytes include signed zero',()=>{for(const enabled of[false,true]){const f=fixture(enabled);f.e.buckets.get('b1').data[24]=-0;const stream=f.e.instanceStream(0);stream.data=new Float32Array(1);snapshot(f,0);const lastPointer=f.events.findLastIndex(x=>x[0]==='pointer'),upload=f.events.findIndex(x=>x[0]==='upload');assert(lastPointer<upload);assert.equal(f.events.filter(x=>x[0]==='upload').length,1);assert(Object.is(stream.data[28+24],-0));}});
