const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const APP=path.resolve(__dirname,'..'),plain=v=>JSON.parse(JSON.stringify(v));
function load(candidate=false){let found=false;const c=vm.createContext({console,document:{createElement:()=>({getContext:()=>({scale(){}})})}});vm.runInContext('var YY={}',c);c.YY.CAMPUS=JSON.parse(fs.readFileSync(APP+'/data/campus.json'));
for(const n of ['math','geometry','models','eastgate-lions'])vm.runInContext(fs.readFileSync(APP+'/src/'+n+'.js','utf8'),c);
for(const [,file]of fs.readFileSync(APP+'/index.html','utf8').matchAll(/script src="(src\/[^\"]+\.js)"/g)){if(file==='src/perimeter337-vehicle-gates.js'){found=true;if(!candidate)continue;}const code=fs.readFileSync(APP+'/'+file,'utf8');if(file==='src/gates-v33.js'||/Y\.Gates33\.render\s*=/.test(code))vm.runInContext(code,c,{filename:file});}
if(candidate)assert.ok(found,'candidate must be present in the actual page load order');return c;}
function capture(Y,f){const records=[],b=new Y.Builder({add:(key,g,m,col,meta)=>records.push({key,g,m:Array.from(m),col,meta:Array.from(meta)})});b.origin=[4,5,6];b.rotation=.7;b.id=43;b.anim=8;const result=Y.Gates33.render(b,f);return{records,b,result};}
function signature(rs){return plain(rs.map(r=>[r.key,r.g.v,r.m,r.col,r.meta]));}
test('real page chain preserves every original shelter vertex, transform and end panel, appending south-only gate',()=>{const c=load(),Y=c.YY,f=Y.CAMPUS.features.find(f=>f.properties.pickId===766),before=plain(f.geometry),old=capture(Y,f),current=load(true);const now=capture(current.YY,current.YY.CAMPUS.features.find(f=>f.properties.pickId===766));assert.deepEqual(signature(now.records.slice(0,old.records.length)),signature(old.records));assert.equal(now.records.filter(r=>r.key==='southeast33-blue-canopy').length,2);assert.equal(now.records.filter(r=>r.key==='gate766-east-arched-end').length,2);assert.deepEqual(plain(current.YY.CAMPUS.features.find(f=>f.properties.pickId===766).geometry),before);assert.deepEqual(plain([now.b.origin,now.b.rotation,now.b.id,now.b.anim]),[[4,5,6],.7,43,8]);const added=now.records.slice(old.records.length);assert.ok(added.length>0&&added.length<=8);assert.ok(added.some(r=>r.col==='#aeb8b5'));assert.ok(added.some(r=>r.col==='#303936'));assert.ok(added.some(r=>r.col==='#a33e39'));const pts=[];for(const r of added){assert.equal(r.meta[1],766);assert.ok(r.m.every(Number.isFinite)&&r.g.v.every(Number.isFinite));for(let i=0;i<r.g.v.length;i+=8)pts.push(Y.M.apply(r.m,[...r.g.v.slice(i,i+3),1]));}assert.ok(pts.every(p=>p[2]>f.geometry.coordinates[1]+1.5),'south side only, central and hidden north side remain clear');assert.ok(Math.max(...pts.map(p=>p[1]))<1.5);assert.equal(now.result.currentAccessVerified,false);});
test('unrelated gate wrappers and emission failure retain behavior/state',()=>{const c=load(),Y=c.YY,f=Y.CAMPUS.features.find(f=>f.properties.pickId===765),before=capture(Y,f),current=load(true),New=current.YY;assert.deepEqual(signature(capture(New,New.CAMPUS.features.find(f=>f.properties.pickId===765)).records),signature(before.records));const g=New.CAMPUS.features.find(f=>f.properties.pickId===766),b=new Y.Builder({add(key){if(key==='perimeter337-se-silver')throw Error('rejected');}});b.origin=[2,3,4];b.rotation=.4;b.id=7;b.anim=9;assert.throws(()=>New.Gates33.render(b,g),/rejected/);assert.deepEqual(plain([b.origin,b.rotation,b.id,b.anim]),[[2,3,4],.4,7,9]);});
