const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const src=path.resolve(__dirname,'../src'),appSource=fs.readFileSync(path.join(src,'app-v29.js'),'utf8'),networkSource=fs.readFileSync(path.join(src,'network.js'),'utf8');
function appFunction(name){const code=appSource.split('\n').find(line=>line.startsWith(`function ${name}(`));assert(code,`Actual app function missing: ${name}`);return code;}
function setup(){
 const ctx=vm.createContext({YY:{}});vm.runInContext(networkSource,ctx,{filename:'network.js'});const Y=ctx.YY;
 // Actual Network.build computes intersections, node identities and shortest paths.
 const network=Y.Network.build([{points:[[0,0],[10,0],[20,0]],w:3},{points:[[10,-10],[10,10]],w:3},{points:[[100,100],[110,100]],w:3}]);
 const feature=(id,centre)=>({properties:{pickId:id,centre}}),features=[feature(1,[.02,.01]),feature(2,[.04,-.03]),feature(3,[19.9,0]),feature(4,[100,100])],by=new Map(features.map(f=>[f.properties.pickId,f]));
 const elements={'route-from':{value:'1'},'route-to':{value:'3'},'route-status':{},'route-progress':{value:0,disabled:true},'route-play':{disabled:true}},orbit={};
 Object.assign(ctx,{Y,by,campus:{network},point:f=>f.properties.centre,$:id=>elements[id],state:{routeEdges:new Set()},route:null,routePlaying:false,routeDistance:0,mode:'3d',orbit,drawPlan:()=>{},say:()=>{}});
 vm.runInContext(appFunction('planRoute')+'\n'+appFunction('moveAlong'),ctx,{filename:'app-v29.js:selected-functions'});
 const plan=id=>{elements['route-to'].value=String(id);vm.runInContext('planRoute()',ctx)};
 return{ctx,elements,plan,move:()=>vm.runInContext('moveAlong()',ctx),Y,network,by,orbit};
}
test('distinct objects snapped to the same road point have no playable segment',()=>{const h=setup();assert.notDeepEqual(h.by.get(1).properties.centre,h.by.get(2).properties.centre);const a=h.Y.Network.nearest(h.network,h.by.get(1).properties.centre),b=h.Y.Network.nearest(h.network,h.by.get(2).properties.centre);assert.equal(a.id,b.id);assert.equal(h.Y.Network.route(h.network,a.p,b.p).length,0);h.plan(2);assert.equal(h.ctx.route,null);assert.equal(h.elements['route-play'].disabled,true);assert.equal(h.elements['route-progress'].disabled,true);assert.equal(Number(h.elements['route-progress'].value),0);h.move();assert.equal(Number(h.elements['route-progress'].value),0);assert.equal(h.elements['route-status'].textContent,'这两个位置之间没有需要浏览的路段。');});
test('positive route uses the real solver and moveAlong still advances normally',()=>{const h=setup();h.plan(3);assert.equal(h.ctx.route.length,20);const expected=h.Y.Network.route(h.network,[0,0],[20,0]);assert.equal(JSON.stringify(h.ctx.route),JSON.stringify(expected));assert.deepEqual([...h.ctx.state.routeEdges],Array.from(h.Y.Network.routeEdges(h.network,expected)));assert.equal(h.elements['route-play'].disabled,false);h.ctx.routeDistance=7;h.move();assert.equal(h.elements['route-progress'].value,'350');assert.deepEqual(Array.from(h.orbit.target),[7,1,0]);});
test('switching positive to same-point clears playback and edges, and switching back works',()=>{const h=setup();h.plan(3);h.ctx.routeDistance=7;h.ctx.routePlaying=true;h.move();assert(h.ctx.state.routeEdges.size>0);h.plan(2);assert.equal(h.ctx.route,null);assert.equal(h.ctx.routePlaying,false);assert.equal(h.ctx.routeDistance,0);assert.equal(h.ctx.state.routeEdges.size,0);h.move();assert.equal(Number(h.elements['route-progress'].value),0);h.plan(3);assert.equal(h.ctx.route.length,20);assert.equal(h.elements['route-play'].disabled,false);assert.equal(Number(h.elements['route-progress'].value),0);});
test('disconnected target clears old playback and edges and never creates a synthetic connector',()=>{const h=setup();h.plan(3);h.ctx.routePlaying=true;h.ctx.routeDistance=7;h.move();h.plan(4);assert.equal(h.ctx.route,null);assert.equal(h.ctx.routePlaying,false);assert.equal(h.ctx.routeDistance,0);assert.equal(h.ctx.state.routeEdges.size,0);assert.equal(h.elements['route-play'].disabled,true);assert.equal(h.elements['route-progress'].disabled,true);const value=h.elements['route-progress'].value;h.move();assert.equal(h.elements['route-progress'].value,value);assert(Number.isFinite(Number(value)));assert.match(h.elements['route-status'].textContent,/未连通/);h.plan(3);assert.equal(Number(h.elements['route-progress'].value),0);assert.equal(h.elements['route-play'].disabled,false);});
