const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const source=fs.readFileSync(require('path').join(__dirname,'../src/shaoyuan119-landing326.js'),'utf8'),f={properties:{pickId:119,id:'way/240832231'}};
require('node:test')('landing wrapper preserves original exceptions and restores add ownership',()=>{for(const own of [true,false]){const original=()=>{},engine=own?{add:original}:Object.create({add:original}),failure=new Error('renderer-original');const ctx=vm.createContext({YY:{Architecture30:{render(){throw failure;}}}});vm.runInContext(source,ctx);assert.throws(()=>ctx.YY.Architecture30.render({e:engine},f),e=>e===failure);assert.equal(engine.add,original);assert.equal(Object.hasOwn(engine,'add'),own);}
const engine={add(){}},original=engine.add,ctx=vm.createContext({YY:{Architecture30:{render(){return 'completed';}}}});vm.runInContext(source,ctx);assert.throws(()=>ctx.YY.Architecture30.render({e:engine},f),/Expected one existing top tread/);assert.equal(engine.add,original);assert.equal(ctx.YY.Architecture30.render({e:engine},{properties:{pickId:0}}),'completed');console.log('4 checks passed: original error identity, own/inherited restoration, post-success count guard, unrelated fallback');

});
require('node:test')('complete chain changes exactly one existing landing instance and preserves cached meshes',()=>{
 const path=require('path'),crypto=require('crypto'),APP=path.resolve(__dirname,'..');
 function capture(skip){const ctx=vm.createContext({console,atob,document:{createElement:()=>({getContext:()=>new Proxy({measureText:s=>({width:s.length*20})},{get:(o,k)=>o[k]||(()=>{})})})}});vm.runInContext('var YY={}',ctx);
 for(const [,name]of fs.readFileSync(APP+'/index.html','utf8').matchAll(/script src="src\/(.*?)\.js"/g)){if(name==='scene-v29')break;if(skip&&name==='shaoyuan119-landing326')continue;vm.runInContext(fs.readFileSync(APP+'/src/'+name+'.js','utf8'),ctx,{filename:name});}
 const Y=ctx.YY,e=Object.assign(Object.create(Y.Engine.prototype),{buckets:new Map(),stats:{instances:0}}),rows=[],original=e.add;e.add=function(k,g,m,c,p,uv){original.call(this,k,g,m,c,p,uv);const v=this.buckets.get(k).geometry.v;rows.push({k,hash:crypto.createHash('sha256').update(Buffer.from(v.buffer,v.byteOffset,v.byteLength)).digest('hex'),m:Array.from(m),c,p:Array.from(p),uv:uv&&Array.from(uv)});};const b=new Y.Builder(e),f=Y.CAMPUS.features.find(f=>f.properties.pickId===119),result=Y.Landscape42.withElevation(b,f,()=>Y.Architecture30.render(b,f,(k,g,c,mat,id)=>e.add(k,g,Y.M.identity(),c,[mat,id,0,0])));return {rows,datum:Y.Shaoyuan119Landing326,result};}
 const a=capture(true),b=capture(false);assert.equal(a.rows.length,563);assert.equal(b.rows.length,a.rows.length);assert.deepEqual(JSON.parse(JSON.stringify(a.result)),JSON.parse(JSON.stringify(b.result)));
 const changes=[];for(let i=0;i<a.rows.length;i++){assert.deepEqual({...a.rows[i],m:null},{...b.rows[i],m:null});if(JSON.stringify(a.rows[i].m)!==JSON.stringify(b.rows[i].m))changes.push(i);}assert.deepEqual(changes,[529]);
 assert.ok(b.datum.gap>.3&&b.datum.gap<.5);assert.equal(b.datum.base,.045);assert.ok(Math.abs(b.datum.top-b.datum.backingBottom)<1e-6);assert.ok(Math.abs(b.datum.newDepth-b.datum.depth-b.datum.gap)<1e-8);
});
