// Small real cache fixtures; no browser, scene bake, private path or large decoded snapshot.
const fs=require('fs'),vm=require('vm'),path=require('path'),crypto=require('crypto'),assert=require('assert/strict'),test=require('node:test');
const app=path.resolve(__dirname,'..'),fixture=require('./fixtures/shared-pages208.json');
const fixtures=fixture.pages.map(page=>page.map(f=>{const vertex=Buffer.from(f.vertex,'base64'),indices=f.indices?Buffer.from(f.indices,'base64'):null,data=Buffer.from(f.data,'base64');const expanded=indices?Buffer.concat(Array.from({length:f.mesh.vertexCount},(_,i)=>{const index=indices.readUInt16LE(i*2);assert.ok(index<f.mesh.uniqueVertexCount);return vertex.subarray(index*32,index*32+32);})):vertex;assert.equal(crypto.createHash('sha256').update(expanded).digest('hex'),f.mesh.hash);assert.equal(crypto.createHash('sha256').update(data).digest('hex'),f.bucket.dataHash);return {...f,vertex,indices,data,expanded};}));
const Y={},ctx=vm.createContext({YY:Y,performance,Float32Array,Uint16Array,Uint32Array,console});for(const name of['math','engine'])vm.runInContext(fs.readFileSync(path.join(app,'src',name+'.js'),'utf8'),ctx,{filename:name+'.js'});
function setup(f,mutate){let id=0,vao=null,bindings={};const uploads=[],deletes=[],draws=[];const g=new Proxy({createBuffer:()=>({id:++id}),createVertexArray:()=>({id:++id,attrs:{}}),bindVertexArray:v=>vao=v,bindBuffer:(k,v)=>{bindings[k]=v;if(k==='ELEMENT_ARRAY_BUFFER'&&vao)vao.ibo=v;},bufferData:(k,v)=>{bindings[k].bytes=typeof v==='number'?Buffer.alloc(v):Buffer.from(new Uint8Array(v.buffer,v.byteOffset,v.byteLength));uploads.push({kind:'allocate',id:bindings[k].id,bytes:bindings[k].bytes.length,k});},bufferSubData:(k,offset,v)=>{assert.ok(v.byteLength<=8192);bindings[k].bytes.set(new Uint8Array(v.buffer,v.byteOffset,v.byteLength),offset);uploads.push({kind:'sub',id:bindings[k].id,bytes:v.byteLength,k});},vertexAttribPointer:(a,n,type,norm,stride,offset)=>{vao.attrs[a]={buffer:bindings.ARRAY_BUFFER,offset,stride}},drawElementsInstanced:(mode,count,type,offset,instances)=>{const bytes=[],width=type==='UNSIGNED_SHORT'?2:4;for(let ins=0;ins<instances;ins++)for(let i=0;i<count;i++){const j=width===2?vao.ibo.bytes.readUInt16LE(offset+i*width):vao.ibo.bytes.readUInt32LE(offset+i*width),a=vao.attrs[0],d=vao.attrs[3];bytes.push(a.buffer.bytes.subarray(a.offset+j*32,a.offset+j*32+32),d.buffer.bytes.subarray(d.offset+ins*112,d.offset+ins*112+112));}draws.push({count,offset,instances,type,bytes:Buffer.concat(bytes)});},deleteBuffer:b=>{if(b)deletes.push(b.id);}},{get:(o,k)=>k in o?o[k]:k===k.toUpperCase()?k:()=>{}});
 const origin=f[0].mesh.buffer.offset,manifest={version:2,meshes:f.map(x=>({...x.mesh,buffer:{...x.mesh.buffer,offset:x.mesh.buffer.offset-origin}})),buckets:f.map((x,i)=>({...x.bucket,mesh:i})),stats:{}};if(mutate)mutate(manifest);const e=Object.assign(Object.create(Y.Engine.prototype),{gl:g,visibilityCaches:new Map(),stats:{},state:{specializedFoliage:false,specializedCeramic:false,skyAfterOpaque:false},shadowTarget:{tex:{}},reflectTarget:{tex:{}},releaseProgramStages(){},disposeTarget(){},stateUniforms(){},sampler(){},sky(){}});e.beginPrepared(manifest);const bs=[...e.buckets.values()];bs.forEach((b,i)=>Object.assign(b,{data:new Float32Array(f[i].data.buffer.slice(f[i].data.byteOffset,f[i].data.byteOffset+112)),spatial:new Float32Array(5),materials:new Set([f[i].data.readFloatLE(80)]),uniformMaterial:f[i].data.readFloatLE(80),foliageIsotropic:false,preparedCompiled:true}));const whole=Buffer.concat(f.map(x=>x.vertex)),arr=new Float32Array(whole.buffer.slice(whole.byteOffset,whole.byteOffset+whole.byteLength)),vv=i=>new Float32Array(arr.buffer,manifest.meshes[i].buffer.offset,manifest.meshes[i].buffer.length),ix=i=>new Uint16Array(f[i].indices.buffer.slice(f[i].indices.byteOffset,f[i].indices.byteOffset+f[i].indices.byteLength));return{e,g,bs,vv,ix,uploads,deletes,draws,arr,f,manifest};}
function loaded(f,reverse=false){const s=setup(f);const ids=f.map((_,i)=>i);if(reverse){for(const i of ids.slice().reverse())if(f[i].indices)s.e.preparedIndices(i,s.ix(i));for(const i of ids.slice().reverse())s.e.preparedVertices(i,s.vv(i));}else{for(const i of ids)s.e.preparedVertices(i,s.vv(i));for(const i of ids)if(f[i].indices)s.e.preparedIndices(i,s.ix(i));}return s;}
function expectBytes(f,ids){const out=[];for(const i of ids)for(let j=0;j<f[i].expanded.length;j+=32)out.push(f[i].expanded.subarray(j,j+32),f[i].data);return Buffer.concat(out);}
function draw(s,ids,pass=0){const{e,g,bs}=s,stream={buffer:g.createBuffer()};g.bindBuffer(g.ARRAY_BUFFER,stream.buffer);g.bufferData(g.ARRAY_BUFFER,Buffer.concat(s.f.map(x=>x.data)));const items=ids.map(i=>({b:bs[i],record:{offset:i*28,count:1,vao:e.instanceVAO(bs[i],pass,stream,i*28).vao},ranges:null})),c=e.groupDraws(items,items.length);e.visibleScene=()=>({...c,submitted:ids.length,triangles:ids.reduce((n,i)=>n+s.f[i].mesh.vertexCount/3,0),culled:0});e.main={p:{}};s.draws.length=0;e.draw(e.main,[],[],pass);assert.ok(Buffer.concat(s.draws.map(x=>x.bytes)).equals(expectBytes(s.f,ids)));assert.ok(s.draws.every(x=>x.instances===1));return c;}
test('small real pages upload once without vertex duplication, both arrival orders and detach',async()=>{for(const f of fixtures)for(const reverse of[false,true]){const s=loaded(f,reverse);assert.equal(s.e.pages208.length,1);assert.equal(new Set(s.e.meshResources).size,f.length);assert.equal(s.uploads.filter(x=>x.kind==='allocate'&&x.k==='ARRAY_BUFFER').length,1);assert.equal(s.uploads.filter(x=>x.kind==='allocate'&&x.k==='ELEMENT_ARRAY_BUFFER').length,1);assert.ok(s.uploads.filter(x=>x.kind==='sub').every(x=>x.bytes<=8192));await s.e.finishPrepared(async()=>{});assert.equal(s.e.pageIndexScratch208,null);structuredClone(s.arr.buffer,{transfer:[s.arr.buffer]});assert.equal(s.arr.byteLength,0);s.e.dispose();}});
test('actual full attributes and instances equal for both real pages/all4passes, every singleton and interior holes',()=>{for(const f of fixtures){const s=loaded(f),all=f.map((_,i)=>i);for(const pass of[0,1,2,3]){assert.equal(draw(s,all,pass).drawItems.length,1);draw(s,[],pass);for(const i of all)assert.equal(draw(s,[i],pass).drawItems.length,1);if(f.length>2){const ids=all.filter(i=>i!==1);assert.equal(draw(s,ids,pass).drawItems.length,ids.length===1?1:2);}}s.e.dispose();}});
test('manifest drift, missing keys, nonexclusive references, range/uint32/65535 overrun fallback',()=>{const f=fixtures[0];for(const mutate of[m=>m.buckets[0].key+='-changed',m=>m.meshes[0].hash='changed',m=>m.buckets[0].count=2,m=>m.buckets[1].mesh=0,m=>m.meshes[0].ranges=[[0,3]],m=>m.meshes[0].indexType='uint32',m=>m.meshes[0].buffer.chunk++,m=>{m.meshes[0].uniqueVertexCount=65536;m.meshes[0].buffer.length=65536*8}]){const s=setup(f,mutate);assert.equal(s.e.pages208.length,0);assert.ok(s.e.meshResources.every(x=>!x.page208));}});
test('truncated, repeated, corrupt or failed uploads poison page and refuse all later publication/finish',()=>{const f=fixtures.find(f=>f.some(x=>x.indices));for(const mode of['duplicate','length','index','driver','missing']){const s=mode==='duplicate'?loaded(f):setup(f);if(mode==='duplicate')assert.throws(()=>s.e.preparedVertices(0,s.vv(0)),/Invalid/);if(mode==='length')assert.throws(()=>s.e.preparedVertices(0,new Float32Array(1)),/Invalid/);if(mode==='index'){const i=f.findIndex(x=>x.indices),bad=s.ix(i);bad[0]=65535;assert.throws(()=>s.e.preparedIndices(i,bad),/Out-of-range/);}if(mode==='driver'){s.g.bufferData=()=>{throw Error('driver')};assert.throws(()=>{for(let i=0;i<f.length;i++){s.e.preparedVertices(i,s.vv(i));if(f[i].indices)s.e.preparedIndices(i,s.ix(i));}},/driver/);}assert.throws(()=>s.e.finishPrepared(async()=>{}),/Incomplete/);if(mode!=='missing')assert.throws(()=>s.e.preparedVertices(0,s.vv(0)),/interrupted/);s.e.dispose();const ids=s.uploads.filter(x=>x.kind==='allocate').map(x=>x.id);for(const id of ids)assert.equal(s.deletes.filter(x=>x===id).length,1);}});
test('opaque boundary, mismatched instance bytes/material path/count/ranges never combine',()=>{const s=loaded(fixtures[0]),a={b:s.bs[0],record:{offset:0,count:1}},b={b:s.bs[1],record:{offset:28,count:1}};assert.equal(s.e.groupDraws([a,b],0).drawItems.length,2);for(const mutate of[x=>x.record.count=2,x=>x.record.offset=56,x=>x.ranges=[[3,6]],x=>x.b.data[21]++,x=>x.b.foliageIsotropic=true,x=>x.b.uniformMaterial=25]){const c={...b,record:{...b.record},b:{...b.b,data:new Float32Array(b.b.data)}};mutate(c);assert.equal(s.e.groupDraws([a,c],2).drawItems.length,2);}});
test('partial/full disposal once, repeated disposal, fresh context requires fresh completions',()=>{for(const full of[false,true]){const s=full?loaded(fixtures[0]):setup(fixtures[0]);if(!full)s.e.preparedVertices(0,s.vv(0));const page=s.e.pages208[0];s.e.dispose();s.e.dispose();for(const id of new Set(s.uploads.filter(x=>x.kind==='allocate').map(x=>x.id)))assert.equal(s.deletes.filter(x=>x===id).length,1);assert.equal(s.e.pageIndexScratch208,null);const next=setup(fixtures[0]);assert.notEqual(next.e.pages208[0],page);assert.ok(next.e.meshResources.every(x=>!x.vertexBuffer&&!x.indexBuffer));assert.throws(()=>next.e.finishPrepared(async()=>{}),/Incomplete/);}});

test('uint16 page layout exact65535 boundary, overflowing singleton and oversized members safely fall back',()=>{const split=require('../tools/shared-pages208-layout.cjs');assert.deepEqual(split([32767,32768],x=>x),[[32767,32768]]);assert.deepEqual(split([32767,32768,1],x=>x),[[32767,32768]]);assert.deepEqual(split([40000,30000,30000],x=>x),[[30000,30000]]);assert.deepEqual(split([10,20,65536,5,6],x=>x),[[10,20],[5,6]]);});
test('shared pages keep waterBounds; same hash with animation/material/instance differences refuses merge',()=>{const s=loaded(fixtures[0]),a={b:s.bs[0],record:{offset:0,count:1}},b={b:s.bs[1],record:{offset:28,count:1}};for(const index of[0,20,21,22,23,24,27]){const c={...b,b:{...b.b,data:new Float32Array(b.b.data)}};c.b.data[index]++;assert.equal(s.e.groupDraws([a,c],2).drawItems.length,2);}const t=setup(fixtures[0],m=>m.meshes[0].waterBounds=[1,2,3,4,5,6]);assert.deepEqual(t.e.meshResources[0].waterBounds,[1,2,3,4,5,6]);});
test('missing logical publication despite shared buffers and invalid index type/length poison',()=>{const f=fixtures.find(f=>f.some(x=>x.indices)),i=f.findIndex(x=>x.indices);for(const v of[new Uint16Array(1),new Uint32Array(f[i].mesh.vertexCount)]){const s=setup(f);assert.throws(()=>s.e.preparedIndices(i,v),/Invalid/);assert.ok(s.e.pages208[0].failed);assert.throws(()=>s.e.preparedVertices(0,s.vv(0)),/interrupted/);}const s=setup(f);s.e.preparedVertices(0,s.vv(0));assert.ok(s.e.meshResources[1].vertexBuffer);assert.throws(()=>s.e.finishPrepared(async()=>{}),/Incomplete/);});
test('original same-resource multi-instance merge remains intact without mutating logical records',()=>{
 const {e}=setup(fixtures[0]),resource={},a={b:{resource,vertexCount:36},record:{offset:0,count:2}},b={b:{resource,vertexCount:36},record:{offset:56,count:3}};
 const g=e.groupDraws([a,b],2);assert.equal(g.drawItems.length,1);assert.equal(g.drawItems[0].record.count,5);assert.equal(a.record.count,2);assert.equal(b.record.count,3);
 assert.equal(e.groupDraws([a,{...b,record:{offset:84,count:3}}],2).drawItems.length,2);
});
test('unpaged uint32 and uint16 nonzero range offsets and nonindexed draws keep original units',()=>{
 for(const pass of[0,1,2,3]){
  const {e,g}=setup(fixtures[0]),trace=[];g.drawElementsInstanced=(mode,count,type,offset,instances)=>trace.push({count,type,offset,instances});g.drawArraysInstanced=(mode,first,count,instances)=>trace.push({first,count,instances});
  const item=(indexType,ranges,vertexCount=12)=>({b:{resource:{indexBuffer:indexType?{}:null,indexType},vertexCount,uniformMaterial:24,foliageIsotropic:false},record:{vao:{},count:2},ranges});
  const items=[item('uint32',null),item('uint32',[[5,6]]),item('uint16',[[3,9]]),item(null,[[6,3]])];e.main={p:{}};e.visibleScene=()=>({drawItems:items,drawClearStart:4,submitted:8,triangles:20,culled:0});e.draw(e.main,[],[],pass);
  assert.deepEqual(trace,[{count:12,type:'UNSIGNED_INT',offset:0,instances:2},{count:6,type:'UNSIGNED_INT',offset:20,instances:2},{count:9,type:'UNSIGNED_SHORT',offset:6,instances:2},{first:6,count:3,instances:2}]);
 }
});
