const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const APP=process.env.PKU_APP||path.resolve(__dirname,'..'),BODY=path.join(APP,'src/westgate-body327.js');let includeBody=false;
// Independent pre-231 scan fixture; keep its ordering and duplicate-key semantics.
const referenceScan="function rectangles(g){const out=[],active=new Map();for(let y=0;y<g.h;y++){const row=new Map();for(let j=0;j<g.r.length;j+=4)if(g.r[j]===y){const x=g.r[j+1],w=g.r[j+2],alpha=g.r[j+3],key=x+','+w+','+alpha;row.set(key,{x,w,alpha});}for(const[k,r]of active)if(!row.has(k)){out.push(r);active.delete(k);}for(const[k,r]of row){if(active.has(k))active.get(k).h++;else active.set(k,{...r,y,h:1});}}out.push(...active.values());return out;}";
const candidateSource=fs.readFileSync(process.env.PLAQUE_SOURCE || path.join(APP,'src/westgate-plaque164.js'),'utf8');
const begin=candidateSource.indexOf('function rectangles(g)'),end=candidateSource.indexOf('\nconst glyphRects=');
assert.ok(begin>=0 && end>begin,'locate production scan');
const original=candidateSource.slice(0,begin)+referenceScan+candidateSource.slice(end);
function capture(source,pick=54,fit=false){
 const ctx=vm.createContext({console,atob,document:{createElement:()=>({getContext:()=>new Proxy({ops:[],stack:[],globalAlpha:1,measureText:s=>({width:s.length*20}),fillRect(...args){this.ops.push({args,alpha:this.globalAlpha,color:this.fillStyle});},save(){this.stack.push([this.globalAlpha,this.fillStyle]);},restore(){[this.globalAlpha,this.fillStyle]=this.stack.pop();}},{get:(o,k)=>o[k]||(()=>{})})})}});vm.runInContext('var YY={}',ctx);
 const names=[...fs.readFileSync(APP+'/index.html','utf8').matchAll(/script src="src\/(.*?)\.js"/g)].map(m=>m[1]);let inserted=0;
 for(const n of names){if(n==='scene-v29')break;if(n==='westgate-body327')continue;if(n==='west-door-normal186-private'&&includeBody)vm.runInContext(fs.readFileSync(BODY,'utf8'),ctx);if(n==='westgate-proportion326')continue;if(n==='westgate-plaque164'){vm.runInContext(source,ctx,{filename:n});inserted++;}else vm.runInContext(fs.readFileSync(APP+'/src/'+n+'.js','utf8'),ctx,{filename:n});}
 assert.equal(inserted,1);if(fit)vm.runInContext(fs.readFileSync(process.env.PROPORTION_SOURCE||path.join(APP,'src/westgate-proportion326.js'),'utf8'),ctx);const Y=ctx.YY,f=Y.CAMPUS.features.find(f=>f.properties.pickId===pick),e=Object.create(Y.Engine.prototype),out=[];e.buckets=new Map();e.stats={instances:0};
 const seen=new WeakSet(),arrays=new WeakMap(),hashes=new WeakMap();const b=new Y.Builder({add(k,g,m,c,p,uv){const first=e.buckets.get(k)?.geometry;Y.Engine.prototype.add.call(e,k,g,m,c,p,uv);const cached=e.buckets.get(k).geometry;if(!seen.has(g)){assert.deepEqual(Array.from(cached.v),Array.from(g.v,Math.fround),'first-key Float32 '+k);seen.add(g);}if(!arrays.has(cached)){arrays.set(cached,Array.from(cached.v));hashes.set(cached,require('node:crypto').createHash('sha256').update(Buffer.from(new Float32Array(cached.v).buffer)).digest('hex'));}if(first)assert.equal(first,cached);out.push({k:k.replace('v30-',''),v:arrays.get(cached),vHash:hashes.get(cached),m:Array.from(m),c,p:Array.from(p),uv:uv&&Array.from(uv)});}});
 const oldAdapter=Y.ArchitectureAdapter.render;Y.ArchitectureAdapter.render=function(...args){const result=oldAdapter.apply(this,args);this.lastResult=result;return result;};const run=()=>Y.Landscape42.withElevation(b,f,()=>Y.Architecture30.render(b,f,(k,g,c,mat,id)=>b.e.add(k,g,Y.M.identity(),c,[mat,id,0,0])));run();const saved=out.slice();out.length=0;run();assert.deepEqual(saved.map(({v,...r})=>r),out.map(({v,...r})=>r),'repeat cache');return{out,Y,b};
}





test('327 affine lower body, rigid upper assemblies, original plaque geometry, normals and restoration',()=>{const near=(a,b,e=2e-6)=>assert.ok(Math.abs(a-b)<e,`${a} != ${b}`);
includeBody=false;const before=capture(candidateSource,54,true);includeBody=true;const after=capture(candidateSource,54,true),M=after.Y.M;
assert.equal(before.out.length,709);assert.equal(after.out.length,709);let minNormalDot=1,changed=0,unchanged=0,plaque=0,doors=0;
function shader(r,j){const cols=[0,1,2].map(k=>r.m.slice(k*4,k*4+3)),raw=r.v.slice(j+3,j+6);return M.norm([0,1,2].map(k=>cols.reduce((s,c,i)=>s+raw[i]*c[k]/M.dot(c,c),0)));}
for(let i=0;i<709;i++){const a=before.out[i],b=after.out[i];assert.equal(a.v.length,b.v.length);assert.deepEqual(a.c,b.c);assert.deepEqual(a.p,b.p);assert.deepEqual(a.uv,b.uv);for(const j of[0,2,4,6,8,10,12,14])assert.equal(a.m[j],b.m[j]);if(JSON.stringify(a)===JSON.stringify(b)){unchanged++;continue;}changed++;
 const q=b.m[5]/a.m[5];
 if(a.k.startsWith('west-door-normal186-')){doors++;for(let j=0;j<a.v.length;j+=8){for(const k of[0,1,2,6,7])assert.equal(a.v[j+k],b.v[j+k]);const na=shader(a,j),nb=shader(b,j),expected=M.norm([na[0],na[1]/q,na[2]]),dot=M.dot(expected,nb);minNormalDot=Math.min(minNormalDot,dot);assert.ok(dot>.999999,`${i} normal ${dot}`);}if(a.p[0]===9)assert.deepEqual(a.m.slice(0,12),b.m.slice(0,12));}
 else {assert.equal(a.vHash,b.vHash);if(a.k.includes('westgate-windows161-lattice'))for(let j=0;j<a.v.length;j+=8){const na=shader(a,j),nb=shader(b,j),expected=M.norm([na[0],na[1]/q,na[2]]),dot=M.dot(expected,nb);assert.ok(dot>.999999,`window ${dot}`);minNormalDot=Math.min(minNormalDot,dot);}}
 if(a.k.startsWith('westgate-plaque164-')){plaque++;assert.deepEqual(a.m.slice(0,13),b.m.slice(0,13));near(b.m[13]-a.m[13],-1.28*.9690287646522834);}
 if(a.k.includes('roof')){assert.deepEqual(a.m.slice(0,13),b.m.slice(0,13));near(b.m[13]-a.m[13],-1.28*.9690287646522834);}
}
assert.equal(plaque,18);assert.equal(doors,288);
const leaves=after.out.filter(r=>r.k.startsWith('west-door-normal186-box-')&&r.c==='#81372c');assert.equal(leaves.length,6);for(const r of leaves){near(r.m[5],4*.9690287646522834*.68);near(r.m[13]-r.m[5]/2,.31*.9690287646522834);}
const lintels=after.out.filter(r=>r.k==='box'&&r.p[0]===20&&Math.abs(r.m[5]-.86*.9690287646522834)<1e-5);assert.equal(lintels.length,3);for(const r of lintels)near(r.m[13]-r.m[5]/2,leaves[0].m[13]+leaves[0].m[5]/2);
for(const id of[55,89]){includeBody=false;const a=capture(candidateSource,id,true);includeBody=true;const b=capture(candidateSource,id,true);assert.deepEqual(a.out,b.out);}
// Both own-property and inherited-property restoration on normal and throwing paths.
for(const own of[false,true])for(const fail of[false,true]){const error=new Error('fixture');const add=()=>{},historic=function(){this.e.add('box',{v:[0,0,0,0,1,0,0,0]},[1,0,0,0,0,1,0,0,0,0,1,0,0,2,0,1],'#a',[20]);if(fail)throw error;return 17;},proto={historicWestGate:historic,westGateLion(){},westGateDoor(){},v9Roof(){},v9Bracket(){},v9PaintedBeam(){}};const b=Object.create(proto);b.e=Object.create({add});if(own){b.historicWestGate=historic;b.e.add=add;for(const k of Object.keys(proto))b[k]=proto[k];}const baseline=Object.getOwnPropertyDescriptors(b),eb=Object.getOwnPropertyDescriptors(b.e),c=vm.createContext({YY:{Architecture30:{render:(b)=>b.historicWestGate()}}});vm.runInContext(fs.readFileSync(BODY,'utf8'),c);try{const r=c.YY.Architecture30.render(b,{properties:{pickId:54,id:'way/226703926'}});assert.equal(r,17);assert.ok(!fail);}catch(e){assert.equal(e,error);assert.ok(fail);}assert.deepEqual(Object.getOwnPropertyDescriptors(b),baseline);assert.deepEqual(Object.getOwnPropertyDescriptors(b.e),eb);}
const fr=after.Y.ArchitectureAdapter.lastResult.frame,sc=after.Y.ArchitectureAdapter.lastResult.scale;let windowRecords=0;for(let i=0;i<709;i++){const a=before.out[i],b=after.out[i],dx=a.m[12]-fr.centre[0],dz=a.m[14]-fr.centre[1],x=(Math.cos(fr.r)*dx-Math.sin(fr.r)*dz)/sc[0],z=(Math.sin(fr.r)*dx+Math.cos(fr.r)*dz)/sc[2],y=a.m[13]/sc[1];if(Math.abs(x)>8.2&&Math.abs(x)<12.6&&z>3.9&&y>1.1&&y<4.9&&!a.k.includes('roof')&&!a.k.includes('lion')&&!a.k.includes('plinth')){if(a.k.startsWith('westgate-windows161-')||a.k==='box'){for(let j=0;j<a.v.length;j+=8){const ay=M.apply(a.m,[...a.v.slice(j,j+3),1])[1],by=M.apply(b.m,[...b.v.slice(j,j+3),1])[1];near(by,.31*sc[1]+.68*(ay-.31*sc[1]),3e-6);}windowRecords++;}}}assert.ok(windowRecords>=30);
const report={windowRecords,records:709,changed,unchanged,doorRecords:doors,plaqueRecords:plaque,minNormalDot,doorWidth:4.26*.6268983387428467,doorHeightBefore:4*.9690287646522834,doorHeightAfter:leaves[0].m[5],widthHeightBefore:4.26*.6268983387428467/(4*.9690287646522834),widthHeightAfter:4.26*.6268983387428467/leaves[0].m[5],rigidUpperDelta:-1.28*.9690287646522834,neighbors:[55,89],restorationCases:4};assert.equal(changed,611);assert.equal(unchanged,98);assert.equal(windowRecords,36);});
