const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const APP=process.env.PKU_APP||path.resolve(__dirname,'..');
// Independent pre-231 scan fixture; keep its ordering and duplicate-key semantics.
const referenceScan="function rectangles(g){const out=[],active=new Map();for(let y=0;y<g.h;y++){const row=new Map();for(let j=0;j<g.r.length;j+=4)if(g.r[j]===y){const x=g.r[j+1],w=g.r[j+2],alpha=g.r[j+3],key=x+','+w+','+alpha;row.set(key,{x,w,alpha});}for(const[k,r]of active)if(!row.has(k)){out.push(r);active.delete(k);}for(const[k,r]of row){if(active.has(k))active.get(k).h++;else active.set(k,{...r,y,h:1});}}out.push(...active.values());return out;}";
const candidateSource=fs.readFileSync(process.env.PLAQUE_SOURCE || path.join(APP,'src/westgate-plaque164.js'),'utf8');
const begin=candidateSource.indexOf('function rectangles(g)'),end=candidateSource.indexOf('\nconst glyphRects=');
assert.ok(begin>=0 && end>begin,'locate production scan');
const original=candidateSource.slice(0,begin)+referenceScan+candidateSource.slice(end);
function capture(source,pick=54,fit=false){
 const ctx=vm.createContext({console,atob,document:{createElement:()=>({getContext:()=>new Proxy({ops:[],stack:[],globalAlpha:1,measureText:s=>({width:s.length*20}),fillRect(...args){this.ops.push({args,alpha:this.globalAlpha,color:this.fillStyle});},save(){this.stack.push([this.globalAlpha,this.fillStyle]);},restore(){[this.globalAlpha,this.fillStyle]=this.stack.pop();}},{get:(o,k)=>o[k]||(()=>{})})})}});vm.runInContext('var YY={}',ctx);
 const names=[...fs.readFileSync(APP+'/index.html','utf8').matchAll(/script src="src\/(.*?)\.js"/g)].map(m=>m[1]);let inserted=0;
 for(const n of names){if(n==='scene-v29')break;if(n==='westgate-proportion326')continue;if(n==='westgate-plaque164'){vm.runInContext(source,ctx,{filename:n});inserted++;}else vm.runInContext(fs.readFileSync(APP+'/src/'+n+'.js','utf8'),ctx,{filename:n});}
 assert.equal(inserted,1);if(fit)vm.runInContext(fs.readFileSync(process.env.PROPORTION_SOURCE||path.join(APP,'src/westgate-proportion326.js'),'utf8'),ctx);const Y=ctx.YY,f=Y.CAMPUS.features.find(f=>f.properties.pickId===pick),e=Object.create(Y.Engine.prototype),out=[];e.buckets=new Map();e.stats={instances:0};
 const seen=new WeakSet(),arrays=new WeakMap(),hashes=new WeakMap();const b=new Y.Builder({add(k,g,m,c,p,uv){const first=e.buckets.get(k)?.geometry;Y.Engine.prototype.add.call(e,k,g,m,c,p,uv);const cached=e.buckets.get(k).geometry;if(!seen.has(g)){assert.deepEqual(Array.from(cached.v),Array.from(g.v,Math.fround),'first-key Float32 '+k);seen.add(g);}if(!arrays.has(cached)){arrays.set(cached,Array.from(cached.v));hashes.set(cached,require('node:crypto').createHash('sha256').update(Buffer.from(new Float32Array(cached.v).buffer)).digest('hex'));}if(first)assert.equal(first,cached);out.push({k:k.replace('v30-',''),v:arrays.get(cached),vHash:hashes.get(cached),m:Array.from(m),c,p:Array.from(p),uv:uv&&Array.from(uv)});}});
 const oldAdapter=Y.ArchitectureAdapter.render;Y.ArchitectureAdapter.render=function(...args){const result=oldAdapter.apply(this,args);this.lastResult=result;return result;};const run=()=>Y.Landscape42.withElevation(b,f,()=>Y.Architecture30.render(b,f,(k,g,c,mat,id)=>b.e.add(k,g,Y.M.identity(),c,[mat,id,0,0])));run();const saved=out.slice();out.length=0;run();assert.deepEqual(saved.map(({v,...r})=>r),out.map(({v,...r})=>r),'repeat cache');return{out,Y,b};
}



test('photo-fit geometry preserves native contour topology, alpha, UV, atlas and orthogonal instance matrices; actual shader normals remain correct',()=>{
const baseline=capture(candidateSource);const candidate=capture(candidateSource,54,true),M=candidate.Y.M,changes=[];assert.equal(baseline.out.length,candidate.out.length);let minDot=1,checkedTriangles=0,maxPositionError=0,maxUVError=0;const rad=baseline.Y.WestgatePlaque164.leanDegrees*Math.PI/180,c=Math.cos(rad),s=Math.sin(rad);
for(let i=0;i<baseline.out.length;i++){const a=baseline.out[i],b=candidate.out[i];if(a.k.startsWith('westgate-plaque164-')){assert.equal(b.k,a.k);assert.deepEqual(a.m,b.m);assert.deepEqual(a.c,b.c);assert.deepEqual(a.p,b.p);assert.deepEqual(a.uv,b.uv);assert.equal(a.v.length,b.v.length);const m=a.m,u=Math.hypot(...m.slice(0,3)),v=Math.hypot(...[0,1,2].map(k=>c*m[4+k]+s*m[8+k])),h=3.3/4.44,t=h*u/v;for(let j=0;j<a.v.length;j+=8){const y=c*a.v[j+1]+s*a.v[j+2],z=-s*a.v[j+1]+c*a.v[j+2],expected=[h*a.v[j],c*t*y-s*z,s*t*y+c*z];for(let k=0;k<3;k++)maxPositionError=Math.max(maxPositionError,Math.abs(expected[k]-b.v[j+k]));for(let k=6;k<8;k++)maxUVError=Math.max(maxUVError,Math.abs(a.v[j+k]-b.v[j+k]));}const cols=[0,1,2].map(k=>m.slice(k*4,k*4+3));for(let j=0;j<b.v.length;j+=24){const ps=[0,8,16].map(k=>M.apply(m,[...b.v.slice(j+k,j+k+3),1]).slice(0,3)),n=M.norm(M.cross(M.sub(ps[1],ps[0]),M.sub(ps[2],ps[0])));for(let k=0;k<3;k++){const raw=b.v.slice(j+k*8+3,j+k*8+6),shader=M.norm([0,1,2].map(axis=>cols.reduce((total,col,j)=>total+raw[j]*col[axis]/M.dot(col,col),0))),dot=M.dot(n,shader);assert.ok(dot>.9999,`${b.k}: ${dot}`);minDot=Math.min(minDot,dot);}checkedTriangles++;}changes.push(a.k);}else assert.deepEqual(a,b);}
assert.equal(changes.length,18);assert.ok(maxPositionError<1e-6);assert.equal(maxUVError,0);assert.deepEqual(baseline.b.ctx.ops,candidate.b.ctx.ops);assert.equal(JSON.stringify(baseline.Y.WestgatePlaque164),JSON.stringify(candidate.Y.WestgatePlaque164));console.log(JSON.stringify({records:baseline.out.length,changedGeometryRecords:changes.length,minShaderNormalDot:minDot,checkedTriangles,maxPositionError,maxUVError}));
});
test('neighbor records unchanged',()=>{for(const id of[55,89])assert.deepEqual(capture(candidateSource,id).out,capture(candidateSource,id,true).out);});
